// Scripted product-tour logic. No network calls anywhere in this file.
// REAL_DAVONEX_POSTS is a static snapshot copied at build time, not fetched
// live; "Read the real post" links open the real davonex.com URL directly,
// which is a normal outbound link, not a fetch this demo performs.

function escapeHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

let creditsBalance = DEMO.credits;
let libraryDemo = null; // { title, addedAt, expiresAt, tickHandle, timeoutHandle }
const LIBRARY_LIFETIME_MS = 15 * 60 * 1000;

function renderCreditsBanner() {
  document.querySelectorAll(".credits-value").forEach(el => {
    el.textContent = creditsBalance.toLocaleString();
  });
}

function renderPackages() {
  const grid = document.getElementById("pricing-grid");
  grid.innerHTML = DEMO.packages.map(p => `
    <div class="plan${p.featured ? " is-pro" : ""}">
      <h3>${escapeHtml(p.name)}</h3>
      <div class="price">${escapeHtml(p.price)}</div>
      <div>${escapeHtml(p.credits)}</div>
      <p>${escapeHtml(p.note)}</p>
    </div>
  `).join("");
}

function renderPresetChips() {
  const row = document.getElementById("preset-row");
  row.innerHTML = GENERATOR_PRESETS.map(p => `
    <button type="button" class="preset-chip" data-preset="${p.id}">${escapeHtml(p.chip)}</button>
  `).join("");
}

function applyPreset(id) {
  const preset = GENERATOR_PRESETS.find(p => p.id === id);
  if (!preset) return;
  document.getElementById("topic-input").value = preset.topic;
  document.getElementById("desc-input").value = preset.description;
  document.getElementById("keywords-input").value = preset.keywords;
  document.querySelectorAll(".preset-chip").forEach(c => c.classList.toggle("is-active", c.dataset.preset === id));
}

function formatCountdown(ms) {
  const total = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function realPostCard(post) {
  const url = `https://davonex.com/blog/${post.slug}/`;
  return `
    <article class="post-card">
      <div class="post-card__img" aria-hidden="true"><span>davonex.com</span></div>
      <h3><a href="${url}" target="_blank" rel="noopener">${escapeHtml(post.title)}</a></h3>
      <p class="excerpt">${escapeHtml(post.excerpt)}</p>
      <div class="post-meta"><span>${escapeHtml(post.date)}</span><span class="dot"></span><span>${escapeHtml(post.read_time)}</span></div>
      <a class="read-link" href="${url}" target="_blank" rel="noopener">Read the real post <span class="arr">&#8594;</span></a>
    </article>
  `;
}

function demoPostCard() {
  const remaining = libraryDemo.expiresAt - Date.now();
  return `
    <article class="post-card post-card--demo">
      <div class="post-card__img" aria-hidden="true"><span>Generated just now</span></div>
      <span class="demo-ribbon">Demo · fabricated · removes in ${formatCountdown(remaining)}</span>
      <h3>${escapeHtml(libraryDemo.title)}</h3>
      <p class="excerpt">${escapeHtml(libraryDemo.description)}</p>
      <div class="post-meta"><span>Generated by this demo</span><span class="dot"></span><span>just now</span></div>
      <button class="btn" data-export="${escapeHtml(libraryDemo.title)}">Export PDF</button>
    </article>
  `;
}

function renderLibrary() {
  const grid = document.getElementById("library-list");
  const countEl = document.getElementById("library-tab-count");
  let html = "";
  let total = REAL_DAVONEX_POSTS.length;
  if (libraryDemo) {
    html += demoPostCard();
    total += 1;
  }
  html += REAL_DAVONEX_POSTS.map(realPostCard).join("");
  grid.innerHTML = html;
  if (countEl) countEl.textContent = `(${total})`;
}

function addToLibrary(title, description) {
  if (libraryDemo) {
    clearInterval(libraryDemo.tickHandle);
    clearTimeout(libraryDemo.timeoutHandle);
  }
  const addedAt = Date.now();
  const expiresAt = addedAt + LIBRARY_LIFETIME_MS;
  libraryDemo = {
    title, description, addedAt, expiresAt,
    tickHandle: setInterval(renderLibrary, 1000),
    timeoutHandle: setTimeout(() => { libraryDemo = null; renderLibrary(); }, LIBRARY_LIFETIME_MS)
  };
  renderLibrary();
}

function renderClientUpdates() {
  document.getElementById("client-name").textContent = DEMO.client.name;
  const list = document.getElementById("updates-list");
  list.innerHTML = DEMO.client.updates.map(u => `
    <div class="update-item">
      <time>${escapeHtml(u.date)}</time>
      <div>${escapeHtml(u.text)}</div>
    </div>
  `).join("");
}

function switchTab(tabId) {
  document.querySelectorAll(".tab").forEach(t => t.classList.toggle("is-active", t.dataset.tab === tabId));
  document.querySelectorAll(".panel").forEach(p => p.classList.toggle("is-active", p.id === `panel-${tabId}`));
}

function runGenerator(e) {
  e.preventDefault();
  const btn = document.getElementById("generate-btn");
  const status = document.getElementById("generate-status");
  const topic = document.getElementById("topic-input").value.trim() || GENERATOR_PRESETS[0].topic;
  const description = document.getElementById("desc-input").value.trim() || GENERATOR_PRESETS[0].description;

  btn.disabled = true;
  status.innerHTML = '<span class="spinner"></span> Checking credit balance...';

  setTimeout(() => {
    creditsBalance -= 100;
    renderCreditsBanner();
    status.innerHTML = '<span class="spinner"></span> Generating post (this can take a minute)...';
  }, 700);

  setTimeout(() => {
    status.innerHTML = '<span class="spinner"></span> Formatting and saving to your library...';
  }, 1900);

  setTimeout(() => {
    addToLibrary(topic, description);
    status.textContent = "Done — see it in your Blog Library tab (removes automatically in 15 minutes).";
    btn.disabled = false;
  }, 2900);
}

function handleExportClick(e) {
  const btn = e.target.closest("[data-export]");
  if (!btn) return;
  const original = btn.textContent;
  btn.disabled = true;
  btn.textContent = "Exporting...";
  setTimeout(() => {
    btn.textContent = "Downloaded ✓";
    setTimeout(() => { btn.textContent = original; btn.disabled = false; }, 1500);
  }, 1000);
}

document.addEventListener("DOMContentLoaded", () => {
  renderCreditsBanner();
  renderPackages();
  renderPresetChips();
  renderLibrary();
  renderClientUpdates();

  document.querySelectorAll(".tab").forEach(t => {
    t.addEventListener("click", () => switchTab(t.dataset.tab));
  });
  document.getElementById("generator-form").addEventListener("submit", runGenerator);
  document.getElementById("preset-row").addEventListener("click", (e) => {
    const btn = e.target.closest("[data-preset]");
    if (!btn) return;
    applyPreset(btn.dataset.preset);
  });
  document.getElementById("library-list").addEventListener("click", handleExportClick);
  document.getElementById("redeem-btn").addEventListener("click", () => {
    const input = document.getElementById("redeem-input");
    const note = document.getElementById("redeem-note");
    if (!input.value.trim()) {
      note.textContent = "Enter a redemption code first.";
      return;
    }
    note.textContent = "This is a demo — no real code is validated here.";
  });
});
