// Scripted product-tour logic. No network calls anywhere in this file.
// REAL_DAVONEX_POSTS is a static snapshot (including full article body and
// hero image) fetched and stored locally at build time, not fetched live;
// opening a card renders that stored content in-page.

function escapeHtml(str) {
  return String(str).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

let creditsBalance = DEMO.credits;
let libraryDemo = null; // { slug, addedAt, expiresAt, tickHandle, timeoutHandle }
let currentPresetSlug = null;
let readerReturnTab = "library";
const LIBRARY_LIFETIME_MS = 15 * 60 * 1000;

function renderCreditsBanner() {
  document.querySelectorAll(".credits-value").forEach(el => {
    el.textContent = creditsBalance.toLocaleString();
  });
}

function renderPackages() {
  const grid = document.getElementById("pricing-grid");
  grid.innerHTML = DEMO.packages.map(p => `
    <div class="plan${p.featured ? " is-pro" : ""}">
      <h3>${escapeHtml(p.name)}</h3>
      <div class="price">${escapeHtml(p.price)}</div>
      <div>${escapeHtml(p.credits)}</div>
      <p>${escapeHtml(p.note)}</p>
    </div>
  `).join("");
}

function autofillRandom() {
  const preset = GENERATOR_PRESETS[Math.floor(Math.random() * GENERATOR_PRESETS.length)];
  currentPresetSlug = preset.slug;
  document.getElementById("topic-input").value = preset.topic;
  document.getElementById("desc-input").value = preset.description;
  document.getElementById("keywords-input").value = preset.keywords;
  document.getElementById("autofill-note").innerHTML =
    `Filled with a real davonex.com post: <strong>${escapeHtml(preset.topic)}</strong>. Generating will add this exact post to the Blog Library as a demo duplicate.`;
}

function formatCountdown(ms) {
  const total = Math.max(0, Math.ceil(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, "0")}`;
}

function realPostCard(post) {
  return `
    <article class="post-card" data-open-post="${post.slug}">
      <div class="post-card__img"><img src="${post.image}" alt="${escapeHtml(post.title)}" loading="lazy"></div>
      <h3>${escapeHtml(post.title)}</h3>
      <p class="excerpt">${escapeHtml(post.excerpt)}</p>
      <div class="post-meta"><span>${escapeHtml(post.date)}</span><span class="dot"></span><span>${escapeHtml(post.read_time)}</span></div>
      <span class="read-link">Read the post <span class="arr">&#8594;</span></span>
    </article>
  `;
}

function demoPostCard() {
  const post = REAL_DAVONEX_POSTS.find(p => p.slug === libraryDemo.slug);
  const remaining = libraryDemo.expiresAt - Date.now();
  return `
    <article class="post-card post-card--demo" data-open-post="${post.slug}" data-is-demo="1">
      <div class="post-card__img"><img src="${post.image}" alt="${escapeHtml(post.title)}" loading="lazy"></div>
      <span class="demo-ribbon">Demo · duplicate · removes in ${formatCountdown(remaining)}</span>
      <h3>${escapeHtml(post.title)}</h3>
      <p class="excerpt">${escapeHtml(post.excerpt)}</p>
      <div class="post-meta"><span>Generated by this demo</span><span class="dot"></span><span>just now</span></div>
      <span class="read-link">Read the post <span class="arr">&#8594;</span></span>
    </article>
  `;
}

function renderLibrary() {
  const grid = document.getElementById("library-list");
  const countEl = document.getElementById("library-tab-count");
  let html = "";
  let total = REAL_DAVONEX_POSTS.length;
  if (libraryDemo) {
    html += demoPostCard();
    total += 1;
  }
  html += REAL_DAVONEX_POSTS.map(realPostCard).join("");
  grid.innerHTML = html;
  if (countEl) countEl.textContent = `(${total})`;
}

function addToLibrary(slug) {
  if (libraryDemo) {
    clearInterval(libraryDemo.tickHandle);
    clearTimeout(libraryDemo.timeoutHandle);
  }
  const addedAt = Date.now();
  const expiresAt = addedAt + LIBRARY_LIFETIME_MS;
  libraryDemo = {
    slug, addedAt, expiresAt,
    tickHandle: setInterval(renderLibrary, 1000),
    timeoutHandle: setTimeout(() => { libraryDemo = null; renderLibrary(); }, LIBRARY_LIFETIME_MS)
  };
  renderLibrary();
}

// ============================ In-page article reader ============================

function openReader(slug, isDemo) {
  const post = REAL_DAVONEX_POSTS.find(p => p.slug === slug);
  if (!post) return;
  readerReturnTab = document.querySelector(".panel.is-active")?.id.replace("panel-", "") || "library";

  const refsHtml = post.references.length ? `
    <div class="reader__refs">
      <h2>References</h2>
      <ol>${post.references.map(r => `<li><a href="${r.url}" target="_blank" rel="noopener">${escapeHtml(r.title)}</a>. <span>(${escapeHtml(r.date)})</span></li>`).join("")}</ol>
    </div>
  ` : "";

  document.getElementById("reader-article").innerHTML = `
    <div class="reader__hero"><img src="${post.image}" alt="${escapeHtml(post.title)}"></div>
    <div class="reader__body">
      ${isDemo ? `<span class="reader__demo-flag">Demo duplicate: matches the real post below, shown here for 15 minutes</span>` : ""}
      <h1>${escapeHtml(post.title)}</h1>
      <div class="reader__meta">
        <span>${escapeHtml(post.by)}</span><span class="dot"></span>
        <span>${escapeHtml(post.date)}</span><span class="dot"></span>
        <span>${escapeHtml(post.read_time)}</span>
      </div>
      <div class="reader__prose">${post.body_html}</div>
      ${refsHtml}
      <div class="reader__provenance">
        This is the real, published content from davonex.com (an actual configured client of the
        real production pipeline), fetched and stored locally so this demo works fully offline.
        Original: <a href="https://davonex.com/blog/${post.slug}/" target="_blank" rel="noopener">davonex.com/blog/${post.slug}/</a>
      </div>
    </div>
  `;
  switchTab("reader");
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function renderClientUpdates() {
  document.getElementById("client-name").textContent = DEMO.client.name;
  const list = document.getElementById("updates-list");
  list.innerHTML = DEMO.client.updates.map(u => `
    <div class="update-item">
      <time>${escapeHtml(u.date)}</time>
      <div>${escapeHtml(u.text)}</div>
    </div>
  `).join("");
}

function switchTab(tabId) {
  document.querySelectorAll(".tab").forEach(t => t.classList.toggle("is-active", t.dataset.tab === tabId));
  document.querySelectorAll(".panel").forEach(p => p.classList.toggle("is-active", p.id === `panel-${tabId}`));
}

function runGenerator(e) {
  e.preventDefault();
  const btn = document.getElementById("generate-btn");
  const status = document.getElementById("generate-status");
  const slug = currentPresetSlug || GENERATOR_PRESETS[0].slug;
  const post = REAL_DAVONEX_POSTS.find(p => p.slug === slug);

  btn.disabled = true;
  status.innerHTML = '<span class="spinner"></span> Checking credit balance...';

  setTimeout(() => {
    creditsBalance -= 100;
    renderCreditsBanner();
    status.innerHTML = '<span class="spinner"></span> Generating post (this can take a minute)...';
  }, 700);

  setTimeout(() => {
    status.innerHTML = '<span class="spinner"></span> Formatting and saving to your library...';
  }, 1900);

  setTimeout(() => {
    addToLibrary(post.slug);
    status.innerHTML = `Done: <strong>${escapeHtml(post.title)}</strong> added to your Blog Library tab (removes automatically in 15 minutes).`;
    btn.disabled = false;
  }, 2900);
}

document.addEventListener("DOMContentLoaded", () => {
  renderCreditsBanner();
  renderPackages();
  renderLibrary();
  renderClientUpdates();

  document.querySelectorAll(".tab").forEach(t => {
    t.addEventListener("click", () => switchTab(t.dataset.tab));
  });
  document.getElementById("generator-form").addEventListener("submit", runGenerator);
  document.getElementById("autofill-btn").addEventListener("click", autofillRandom);

  document.getElementById("library-list").addEventListener("click", (e) => {
    const card = e.target.closest("[data-open-post]");
    if (!card) return;
    openReader(card.dataset.openPost, card.dataset.isDemo === "1");
  });

  document.getElementById("reader-back").addEventListener("click", () => switchTab(readerReturnTab));

  document.getElementById("redeem-btn").addEventListener("click", () => {
    const input = document.getElementById("redeem-input");
    const note = document.getElementById("redeem-note");
    if (!input.value.trim()) {
      note.textContent = "Enter a redemption code first.";
      return;
    }
    note.textContent = "This is a demo: no real code is validated here.";
  });
});
